name: Generate Swift Book PDFs

on:
  schedule:
    - cron: '58 * * * *'  # Every hour at :50

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  