name: Generate Swift Book PDFs

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Optional specific commit SHA of swift-book to build from'
        required: false
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout repository
          uses: actions/checkout@v4
        
        - run: date -u && git rev-parse --abbrev-ref HEAD
